#数据库的链接
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.136.128:3306/mall-pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.128:8848
    alicloud:
      access-key: LTAI5tEDLJuJj6Mjb7MhpRZ9
      secret-key: ZFjmPIHZWUO8w6FcK83CWvTIreqKLQ
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: wangjiang-mall
  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false  #关闭Thymeleaf的缓存
  redis:
    host: 192.168.136.128
    port: 6379
  cache:
    type: redis #SpringCache 缓存的类型是 Redis
    redis:
      time-to-live: 60000 #指定缓存key的过期时间
      #key-prefix: wj_
      use-key-prefix: true
      cache-null-values: true  #是否缓存空值,防止缓存穿透
  session:
    store-type: redis
    redis:
      namespace: spring:session
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8040