#数据库的链接
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.128:8848
  application:
    name: mall-search
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8100