#数据库的链接
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.136.128:3306/mall-oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.128:8848
    alibaba:
      seata:
        tx-service-group: mall-order-group
  application:
    name: mall-order
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    host: 192.168.136.128
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8030
  servlet:
    session:
      timeout: 30m

rocketmq:
  name-server: 192.168.136.128:9876
  producer:
    group: order-producer
  consumer:
    group: order-consumer